name = "anonymous-comment-box"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Custom domain routes
routes = [
  "anon.emilycogsdill.com/*"
]

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }

# KV Namespaces for message queue
[[kv_namespaces]]
binding = "MESSAGE_QUEUE"
id = "f8a0c5236b7044fbbd3ccda02c9001a0"
preview_id = "d72ced350fb9428e91b17909b388ed83"

# Durable Objects (if needed for future features)
# [[durable_objects.bindings]]
# name = "RATE_LIMITER"
# class_name = "RateLimiter"

# Environment variables (to be set in Cloudflare dashboard or wrangler secrets)
# ANTHROPIC_API_KEY - set via: wrangler secret put ANTHROPIC_API_KEY
# GMAIL_ACCESS_TOKEN - set via: wrangler secret put GMAIL_ACCESS_TOKEN  
# RECIPIENT_EMAIL - set via: wrangler secret put RECIPIENT_EMAIL
# AI_WORKER_API_SECRET_KEY - ✓ set via Cloudflare dashboard

# Service binding to AI worker - disabled, using workers.dev URL instead
# [[services]]
# binding = "AI_WORKER"
# service = "ai-worker-api"

# Rate limiting
[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1"

# Simple rate limiting: 10 requests per IP per minute
simple = { limit = 10, period = 60 }

# [build]
# command = "npm run typecheck:src"

[dev]
port = 8787
local_protocol = "http"

# Enable observability
[observability]
enabled = true